FROM pytorch/pytorch:0.4.1-cuda9-cudnn7-runtime

RUN apt-get update && apt-get install -y \
    git \
    && rm -rf /var/lib/apt/lists/*

#RUN git clone https://github.com/pytorch/pytorch.git /pytorch

#WORKDIR /pytorch
#RUN git checkout v0.4.1
#RUN git submodule update --init
#RUN python setup.py install

WORKDIR /app
RUN git clone https://github.com/adiyoss/WatermarkNN.git /app

RUN pip install https://download.pytorch.org/whl/cpu/torch-0.4.1-cp36-cp36m-linux_x86_64.whl
RUN pip install torchvision==0.2.1

# RUN python train.py --batch_size 100 --max_epochs 60 --runname train --wm_batch_size 2 --wmtrain
# RUN python predict.py --model_path checkpoint/model.t7
# RUN python fine-tune.py --lr 0.01 --load_path checkpoint/model.t7 --save_dir checkpoint/ --save_model ftll.t7 --runname fine.tune.last.layer
# RUN python fine-tune.py --lr 0.01 --load_path checkpoint/model.t7 --save_dir checkpoint/ --save_model ftal.t7 --runname fine.tune.all.layers --tunealllayers
# RUN python fine-tune.py --lr 0.01 --load_path checkpoint/model.t7 --save_dir checkpoint/ --save_model rtll.t7 --runname reinit.last.layer --reinitll
# RUN python fine-tune.py --lr 0.01 --load_path checkpoint/model.t7 --save_dir checkpoint/ --save_model rtal.t7 --runname reinit_all.layers --reinitll --tunealllayers

CMD ["/bin/bash"]
